# Generated by Django 4.1.5 on 2023-01-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.TimeField()),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Consulta", "Consulta"), ("Exame", "Exame")],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("is_available", models.BooleanField(default=True)),
                ("cretead_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expire_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
